# Generated by Django 5.2.8 on 2025-11-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the student's full name", max_length=100)),
                ('age', models.IntegerField(help_text="Enter the student's age")),
                ('date', models.DateField(help_text='Enter the date of enrollment')),
            ],
        ),
    ]
